# Generated by Django 5.2.10 on 2026-02-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baloons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='num_planes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
