# Generated by Django 5.2.8 on 2026-05-06 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baloons', '0002_airline_num_planes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirlinePilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baloons.airline')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baloons.pilot')),
            ],
        ),
    ]
