# Generated by Django 5.2.8 on 2026-05-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baloons', '0003_airlinepilot'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='num_sold_planes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
